version: 2
updates:


- package-ecosystem: npm
  directory: ""
  schedule:
    interval: daily
    time: "03:00"
    timezone: "Europe/London"
  open-pull-requests-limit: 20
  reviewers:
  - credfeto
  assignees:
  - credfeto
  allow:
  - dependency-type: all
  commit-message:
    prefix: "[Dependencies]"
  rebase-strategy: "auto"
  versioning-strategy: increase-if-necessary
  labels:
  - "npm"
  - "dependencies"
  - "Changelog Not Required"


- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: "Europe/London"
  open-pull-requests-limit: 99
  reviewers:
  - credfeto
  assignees:
  - credfeto
  allow:
  - dependency-type: all
  commit-message:
    prefix: "[Dependencies]"
  rebase-strategy: "auto"
  labels:
  - "github-actions"
  - "dependencies"
  - "Changelog Not Required"

